source 'https://github.com/CocoaPods/Specs.git'

target 'MXGoogleAnalytics', :exclusive => true do
  pod "MXGoogleAnalytics", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MXGoogleAnalytics", :path => "../"

  
end